### ISSUE TITLE
[Feature Request] Keyboard Macros / Shortcut sequences like ctrl-shift-o as actions.

### ISSUE THREAD

**Issue by djbclark** [toneiv/UbikiTouch#108]
PWAs (persistent web apps) seem to be gaining some traction, and one thing many share is a heavy reliance on a small number of hotkey sequences. 

It'd be awesome if your app could generate them, even if that would require root. It'd also be super-useful for Chrome extensions - while Chrome on Android can't run Chrome extensions yet, Kiwi and some other browsers can, and also Firefox can run many of its extensions in mobile form. Often times the easiest way to access some feature of such an extension is with a keyboard shortcut.

More info on this request (and why alternative keyboards don't really help too much): 
https://forum.xda-developers.com/t/remapping-gestures-buttons-to-keyboard-macros-that-include-control-ctrl-key-for-pwas-without-changing-keyboard.4319655/

**Comment by toneiv** [comment]
Hi, 
Sorry for the late reply.
Is this request still valid? If so, could you give me some examples of applications and associated shortcuts?
Thanks

**Comment by toneiv** [comment]
Inactive
