### ISSUE TITLE
Gesture that controls brightness or volume by simply sliding on the edges

### ISSUE THREAD

**Issue by toneiv** [toneiv/UbikiTouch#111]
Gesture that controls brightness or volume by simply sliding on the edges

**Source** : _PlayStore_

**Comment by Kenkiar** [comment]
Hello. Was this implemented in an update? Is it possible to record an action that implements this feature?

**Comment by toneiv** [comment]
Hello. This feature is the next to be implemented. There is still some work to be done, but it should be available within a few weeks.

**Comment by toneiv** [comment]
Available in 1.12.13

**Comment by Kenkiar** [comment]
Awesome. Thank you for this phenomenal application.
