### ISSUE TITLE
Bottom gesture activates on touch.

### ISSUE THREAD

**Issue by alanDliang** [toneiv/UbikiTouch#120]
Loving this app so far however the bottom "swipe up" for homescreens seems to get triggered on a slight touch instead of a swipe. 

This then leads to accidental home screen triggers when typing on a keyboard and hitting the space button.

I tried to make the trigger position and thickness as small as possible and as thin as possible but it still seems to trigger when touched and not on "swipped".

It's basically the only complain I have on this app keep up the good work!
![Screenshot_2021-12-21-13-02-52-455_eu toneiv ubktouch](https://user-images.githubusercontent.com/23610732/146977287-dfb07e2e-4108-4bc8-9ce2-a3515b421203.jpg)

**Comment by toneiv** [comment]
Thank you for your feedback. Have you explored the options under "Misc / Keyboard behavior"? It seems to me that the option "Prevent bottom keyboard conflicts" could answer your problem. Do not hesitate to send me a feedback.
