### ISSUE TITLE
Vertical Trigger Position after fullscreen video

### ISSUE THREAD

**Issue by Toksxfoile03** [toneiv/UbikiTouch#126]
Hi!
I've been using the app for years and have never encountered a problem. But when i changed to my new phone (Pixel 6a, android 13) i'm getting a bug where after watching fullscreen videos like youtube, the "vertical trigger position" gets limited to the values 0 to about 40 after exiting the fullscreen video. 
The only fix i found was to reactivate the app again or restart the phone.

**Comment by toneiv** [comment]
Hello, 
Unfortunately I can't reproduce this problem with a device similar to yours.
Can you send me a video showing the problem and point me to the following: 
- do you use system gestures on your android system?
- Do you have an option enabled for trigger handling when rotating in UbikiTouch?
Thanks

**Comment by Toksxfoile03** [comment]
Ah is that so. If that's the case, i'd be more than happy to send a video!
In regards to your other questions;

- i use the 3 button navigation because the gesture one sometimes overlaps with the app, and I'm more used to the 3 buttons.
- as for trigger handling, I'm sorry but I'm unfamiliar with that option.

as for the video, please see it here:
https://youtu.be/_4Lo6xxAFBA

as you can see after a few tries with full screen, it would not work after a while. i should've also included it in the video but it will work correctly again after restarting the app (in the app > burger menu > the toggle in the top left)
also, it would that the app also sometimes doesn't work while in full screen.

I hope the video helps in some way, thank you.

**Comment by Toksxfoile03** [comment]
Great news! After trying out version 1.13.1 for an hour or so, it seems the issue has already been resolved. The feedback/response from the app while in full screen videos are much more consistent now. Thank you!

**Comment by toneiv** [comment]
Thanks for your feedback
