### ISSUE TITLE
System Write Permission bug [UbikiTouch 1.13.4]

### ISSUE THREAD

**Issue by resiehnnes** [toneiv/UbikiTouch#128]
In the latest version 1.13.4 auto rotate toggle gesture stopped working telling me that I have to grant System Write Permission, which was already granted and working fine in the previous version. Clearing up data didn't help. What actually helped is when I granted 'Write Secure Settings' permission through ADB.

Another thing to mention is in Navigation Bar menu when the toggle is OFF it shows: "The navigation bar is hidden" but it actually is not hidden, and when you switch the toggle on it gets hidden but it shows "The navigation bar is visible"

Huawei P30 Pro (VOG-L29)
Android 10

**Comment by toneiv** [comment]
Merci pour m'avoir signalé le problème. Un correctif est disponible dans la version 1.13.5
