### ISSUE TITLE
issue on Fold phones

### ISSUE THREAD

**Issue by me7tarfeek** [toneiv/UbikiTouch#129]
The buttom gesture size does not adjust with folding and unfolding the phone. The only solution now is to switch of/on the application in order to adjust.
Other than that, the app is outstanding..

**Comment by me7tarfeek** [comment]
Any feedback please? Thanks in advance

**Comment by toneiv** [comment]
I haven't been able to reproduce this problem at the moment, but I do plan to propose a solution soon. Thank you for your patience.

**Comment by me7tarfeek** [comment]
Thanks for your feedback.. I tried to upload a video here that shows the issue but I could not…

**Comment by me7tarfeek** [comment]
[video](https://drive.google.com/file/d/140h_YBIzR13t0mBRh7OiPL5wQkQImJBk/view?usp=drivesdk) 

Here is the video. It start with phone unfolded with three triggers at the buttom. I put diffirent colors for triggers to make it clear. When folded, triggers are overlapped until I turn the app on/off.

**Comment by toneiv** [comment]
Thanks for the video, it's very useful. I'll try to come up with a solution as soon as possible and keep you posted.

**Comment by toneiv** [comment]
This problem is normally resolved in version 1.13.9 available on the Play Store.

**Comment by me7tarfeek** [comment]
Oh my God.. It works.. What a great and swift support.

Thanks a lot
