### ISSUE TITLE
Add double tap to Trigger actions

### ISSUE THREAD

**Issue by LordSithek** [toneiv/UbikiTouch#138]
Hello, I recently started to use your excellent app, it's one of the best (if not THE best) of its kind in the market. However, this one action I miss very much because I'm used to use it on other devices/apps. Is it possible to add double tap to Trigger actions? Thank you in advance.

**Comment by toneiv** [comment]
Thank you for this suggestion

**Comment by toneiv** [comment]
Done in 1.14.0
