### ISSUE TITLE
Run Macrodroid macros from Ubiki Touch menu?

### ISSUE THREAD

**Issue by Makstuff** [toneiv/UbikiTouch#140]
Could there be a way how I can run Macrodroid macros from the Ubiki Touch menu? That would be the last puzzle piece missing for my perfect setup.

I looked through all the options of both apps and couldn't find any obvious way to do it, but maybe there's some weird hack/workaround that I didn't think of?

**Comment by toneiv** [comment]
Thank you for your interest in my application. It's quite possible to launch a Macrodroid action from Ubikitouch: to do so, select "Shortcuts" / "Macrodroid shortcuts" and then the action you've defined in Macrodroid. I hope this meets your needs.

**Comment by Makstuff** [comment]
Ooh, perfect, dunno how I could miss that, thanks a lot!
