### ISSUE TITLE
Regural expressions

### ISSUE THREAD

**Issue by Pokrzywnik** [toneiv/UbikiTouch#46]
Hi, i wanted to know what are examples of right syntax when entering 'regural expressions'. Tooltip shows that we can use them but I have no idea what syntax is. 

For example I wanted to click on any number within 100-200 and do action. 

Another example if that's possible: click on text with variable. I have a text that changes on every click so ubiki can use it only once and stopped works. It is "some text 2493" and after every click it goes down by 1. Is it possible to find it and click when number is chanigng? When I typed my text without a number it does not work.

**Comment by toneiv** [comment]
Hi.
For your first request (any number within 100-200) you could try this : "(1|2)\d+"
I'm not sure I quite understand your second request : you could record your action with "some text \d+" to match "some text" followed by any digit. 
Hope this helps you.

**Comment by Pokrzywnik** [comment]
Ah thanks, that makes sense. I wasn't aware of syntax, for second one I
used 'text *' and it worked :) now im fully aware of all things I can do
and it's great! Thanks for response and keep on doing great work,
Yours sincerely, Frodo


niedz., 27 paź 2019, 13:23 użytkownik toneiv <notifications@github.com>
napisał:
