### ISSUE TITLE
White bars to left and right of screen?

### ISSUE THREAD

**Issue by ITCMD** [toneiv/UbikiTouch#57]
Hi there, I'm running UT on an Andoird S10 with secure settings enabled. I love the features of the app, however I'm really annoyed by these big grey bars on the left and right middle as seen here:
![img](https://lh3.googleusercontent.com/ZMlEewpAonmLssRlUYdOYll-Q9Z7L1FMhZxJUuk_iZIF_i3unx20wvuTvzBBAv0CsBl9dtcXgK3qahkLfGZxUmNdnw9U7iEnOhl4nsC6875V7ahOjBu58VQAs9a3jKUFL5JcRAymlQQ=w462-h975-no)
Any way to get rid of those?

**Comment by toneiv** [comment]
Hi. You can configure the color and transparency of the triggers in "Left-Right-Bottom Side / Trigger Look / Color and transprency of the tiggers".

**Comment by ITCMD** [comment]
Well I would still like to see the triggers, however I don't want those big grey bars on my screen when not using them...

**Comment by ITCMD** [comment]
Thank you! I figured out what you meant.
