### ISSUE TITLE
Option to use sound instead of vibrating

### ISSUE THREAD

**Issue by lfom** [toneiv/UbikiTouch#89]
Hello!

First, thanks for this nice tool, and for making a free working version (not crippled) as well.

Some devices, mostly tablets, do not have vibration, and large screens are the ones that would benefit the most from gestures. Please consider adding an option for clicks also. A sound (like a toggle, similar to key typing) would be very useful IMO. If it could denote the secondary action being triggered (second sound, different pitch), even more.

Thanks again. Regards.

**Comment by toneiv** [comment]
Hello! 
Thank you for this suggestion. It is a good idea and should be available soon.
Regards

**Comment by lfom** [comment]
@toneiv I have installed the app and joined beta, I will be more than glad to provide feedback when it is released. Thank you.

**Comment by toneiv** [comment]
@lfom it's available in 1.9.4 beta if you wish to test

**Comment by lfom** [comment]
@toneiv Hello, again. I have installed 1.9.4 beta, but unfortunately sound does not work. I got this from logcat, maybe it helps:

`
2020-12-30 14:02:26.449 27620-27620/? W/ubkTouchProcess: type=1400 audit(0.0:105913): avc: denied { read } for name="u:object_r:kirin_audio_prop:s0" dev="tmpfs" ino=12475 scontext=u:r:untrusted_app:s0:c19,c258,c512,c768 tcontext=u:object_r:kirin_audio_prop:s0 tclass=file permissive=0
`

![device-2020-12-30-140707](https://user-images.githubusercontent.com/15659999/103366006-3804e600-4aa0-11eb-878d-c23c5f1074bb.png)

**Comment by toneiv** [comment]
@lfom Hello
I have not been able to reproduce this behaviour.
Here are the tests carried out: 

Case 1
- Device in normal mode
- Sound activation in UbikiTouch
- The sound can be heard
- Device in vibrate mode
- No sound
- Appliance in silent mode
- No sound
- Device in normal mode 
- The sound can be heard

Case 2:
- Appliance in silent mode
- Sound activation in UbikiTouch
- No sound
- Device in vibrate mode
- No sound
- Device in normal mode
- The sound can be heard

Can you give me the procedure to reproduce the malfunction you mention and the log associated? 
Also, can you tell me what your device is and if you use a custom rom?

**Comment by lfom** [comment]
@toneiv I did the same exactly, case 1 and 2. Once sound is disabled, UbikiTouch stops making sound even when enabled again, it comes back only when the app is force closed and started again. It was tested in a Huawei phone with EMUI 9.1.

**Comment by toneiv** [comment]
@Ifom I have not been able to reproduce the problem but I have made some minor changes that may have an impact in the latest version (1.9.5). Don't hesitate to tell me if it makes a difference.

**Comment by lfom** [comment]
@toneiv No difference related to sound, unfortunately. I have noticed that vibration works fine, and sound only stops if you actually activate any UbikiTouch action while in silent mode, i.e. if sound is working in normal sound mode, it keeps working if I change the device sound mode until it goes back to normal mode without using any UbikiTouch gesture in silent mode. The vibration seems to work fine tho: if I enable both sound and vibration, only sound stops if a gesture is used while the device is in silent mode.

**Comment by lfom** [comment]
@toneiv I have installed v1.9.5 on a Fire HD8 with latest FireOS (Android Pie) and sound seems to work fine. It does not have vibration (that is why I requested this feature in first place), so it only enables/disables notifications sound and it works perfectly.

So I guess the problem with EMUI 9.1 is something else. But issue #91 still persists.

Thanks again. Regards.

**Comment by toneiv** [comment]
@lfom OK, got it. As soon as I can get access to an EMUI system I will try to reproduce the problem. Thank you for reporting it. Regards.
