### ISSUE TITLE
Prevent starting of secondary service (Custom Actions)

### ISSUE THREAD

**Issue by lfom** [toneiv/UbikiTouch#91]
Some users may not need Custom Actions and/or don't wanna give permissions to Accessibility beyond the Menu category (home, back, etc, only basic actions). But even if the permission is not granted, the service is started and uses memory (not much, but still uses). IMO the Custom Actions permission should be included in the Optional Permissions group, and the service started only if the permission is granted.

Regards

**Comment by toneiv** [comment]
This seems entirely justified. I note this for a future version. Thank you for the suggestion.

**Comment by lfom** [comment]
@toneiv Hello! I have installed latest beta version from PlayStore, and unfortunately the service is started, even when the extra accessibility permission isn't granted. If I stop the service and start it again with only the permission for "menu and general actions" granted ("custom actions is _not_ granted), I still see both services running in the background using Developer Options -> Running services:

- UbikiTouch [Custom Actions]
- UbikiTouch [Menu]

IMO, the [Custom Actions] shouldn't have been started.

Regards.

**Comment by toneiv** [comment]
@lfom Hello. Very sorry for the delay in responding. I have just released a new beta version (1.10.1) and I think it fixes the problem. You may have to reboot for it to take effect.
